services:

  fhir:
    image: hapiproject/hapi:v5.3.0
    container_name: hapi_fhir_server
    ports:
      - "8082:8080"
    environment:
      profiles.active: r4
      spring.datasource.url: jdbc:postgresql://fhirdbserver:5432/hapi02
      spring.datasource.username: admin
      spring.datasource.password: admin
      spring.datasource.driverClassName: org.postgresql.Driver
    depends_on:
      - fhirdbserver

  fhirdbserver:
    image: postgres
    container_name: fhirdbserver
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hapi02
    ports:
      - "5430:5432"
    volumes:
      - postgres_fhir_data:/var/lib/postgresql/data-hapi02

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadminclininai
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - fhirdbserver

  keycloak:
    image: quay.io/keycloak/keycloak
    command: start-dev
    container_name: keycloak_server
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: admin
      KC_DB_USERNAME: admin
      KC_DB_SCHEMA: public
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
    ports:
      - 8081:8080
    depends_on:
      - postgres
  # frontendApp:
  #   build:
  #     context: ../FE
  #     dockerfile: Dockerfile
  #   image: clinic_fe
  #   container_name: clinic_fe
  #   ports:
  #     - "4200:80"
  #   depends_on:
  #     - fhir
  postgres:
    image: postgres
    container_name: keycloak_data_server
    volumes:
      - postgres_data:/var/lib/postgresql/keycloak_data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: "exit 0"
    ports:
      - 5432:5432

volumes:
  postgres_data: {}
  keycloak_data: {}
  postgres_fhir_data: {}
